name: style-transfer

on: [push]

jobs:
  run:
    runs-on: [self-hosted]
    container: 
      image: docker://dvcorg/cml-gpu-py3:latest
      options: --runtime "nvidia" -e NVIDIA_VISIBLE_DEVICES=all

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python neural_style_transfer.py imgs/owl_photo.jpg imgs/georgia_okeefe.jpg results/owl --iter 10
          
          cml-publish final_image.png --md --title 'styled' >> report.md
          cml-send-comment report.md 
          cml-send-github-check report.md 
          
