name: style-transfer

on: [push]

jobs:
  run:
    runs-on: [self-hosted]
    container: 
      image: docker://dvcorg/cml-gpu-py3:latest
      options: --runtime "nvidia" -e NVIDIA_VISIBLE_DEVICES=all

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nvidia-smi 

          
