name: style-transfer

on: [push]

jobs:
  run:
    runs-on: [self-hosted]
    container: docker://dvcorg/cml-py3-gpu:latest

    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          python --version
